apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyExternalIPs
metadata:
  name: deny-external-ips
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
